// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmHsZWh684Eop2-I2nJHixJ7Xm_KzN9uo',
    appId: '1:532085122130:web:1695bbe61b2f6550e82b8b',
    messagingSenderId: '532085122130',
    projectId: 'pixmind-c5231',
    authDomain: 'pixmind-c5231.firebaseapp.com',
    storageBucket: 'pixmind-c5231.firebasestorage.app',
    measurementId: 'G-BZCD5MFLN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEiUkQVzHSIzDIdCtpdoYJDoUr22-CBGk',
    appId: '1:532085122130:android:93f3b0688dc7304be82b8b',
    messagingSenderId: '532085122130',
    projectId: 'pixmind-c5231',
    storageBucket: 'pixmind-c5231.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ9mYQReVIjndYVOlvnGK6KH_WJkMa0KY',
    appId: '1:532085122130:ios:a6b10baf69041ed3e82b8b',
    messagingSenderId: '532085122130',
    projectId: 'pixmind-c5231',
    storageBucket: 'pixmind-c5231.firebasestorage.app',
    iosBundleId: 'com.example.pixmind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ9mYQReVIjndYVOlvnGK6KH_WJkMa0KY',
    appId: '1:532085122130:ios:a6b10baf69041ed3e82b8b',
    messagingSenderId: '532085122130',
    projectId: 'pixmind-c5231',
    storageBucket: 'pixmind-c5231.firebasestorage.app',
    iosBundleId: 'com.example.pixmind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmHsZWh684Eop2-I2nJHixJ7Xm_KzN9uo',
    appId: '1:532085122130:web:7da94ba6f67a3e05e82b8b',
    messagingSenderId: '532085122130',
    projectId: 'pixmind-c5231',
    authDomain: 'pixmind-c5231.firebaseapp.com',
    storageBucket: 'pixmind-c5231.firebasestorage.app',
    measurementId: 'G-BVY5PKQE4K',
  );
}
